In [2]:
import torch

In [ ]:
a = torch.randn(2, 4, 5, 4)
b = torch.randn(1, 1, 4, 3) # Broadcasting of first two dimensions to (2, 4)
c = torch.matmul(a, b)

In [14]:
c.shape

torch.Size([2, 4, 5, 3])

In [16]:
A = torch.tensor([[1.], [2.], [3.], [4.]]) # Column vector
B = torch.tensor([[10., 20., 30.]])   # Row vector

A.shape, B.shape

(torch.Size([4, 1]), torch.Size([1, 3]))

In [ ]:
C = A + B # Broadcasting of both dimensions to (4, 3)
C.shape, C

(torch.Size([4, 3]),
 tensor([[11., 21., 31.],
         [12., 22., 32.],
         [13., 23., 33.],
         [14., 24., 34.]]))

### EinSum Notation

In [5]:
A = torch.randn(2,3)
B = torch.randn(2,3)
#C = torch.einsum('ik, kj -> ij', A, B) # Matrix multiplication
D = torch.einsum('ij, ij -> ij', A, B) # Pointwise multiplication (Hadamard product)

In [7]:
D.shape, D

(torch.Size([2, 3]),
 tensor([[-1.4551, -0.9453,  0.1441],
         [-0.0248,  1.0331,  0.1660]]))

In [ ]:
P = torch.randn(2, 3, 4)
Q = torch.randn(2, 4, 5)
torch.einsum("nij, njk -> nik", P, Q) # Multiplication over the last dimension of P and the second-to-last dimension of Q

tensor([[[ 7.4203e-01,  1.9851e+00,  3.8401e-01,  8.5965e-01,  1.7427e+00],
         [-9.7846e-01, -1.3815e-01, -1.1246e+00, -1.3988e+00,  1.8840e+00],
         [ 1.0087e-01, -4.5902e-04,  6.8646e-01, -4.9151e-01, -5.3480e-01]],

        [[-1.6577e+00,  6.1597e-01, -3.2758e+00, -8.7333e-01,  7.9749e-01],
         [-1.5196e-01,  1.6380e-01, -1.1814e+00,  1.1252e+00,  1.0139e+00],
         [-1.1516e+00, -4.8976e-01, -1.2628e+00, -4.7076e-01,  2.1040e-01]]])