# Torch

## Tensors

In [2]:
import torch

In [ ]:
a = torch.randn(2, 4, 5, 4)
b = torch.randn(1, 1, 4, 3) # Broadcasting of first two dimensions to (2, 4)
c = torch.matmul(a, b)

In [14]:
c.shape

torch.Size([2, 4, 5, 3])

In [16]:
A = torch.tensor([[1.], [2.], [3.], [4.]]) # Column vector
B = torch.tensor([[10., 20., 30.]])   # Row vector

A.shape, B.shape

(torch.Size([4, 1]), torch.Size([1, 3]))

In [ ]:
C = A + B # Broadcasting of both dimensions to (4, 3)
C.shape, C

(torch.Size([4, 3]),
 tensor([[11., 21., 31.],
         [12., 22., 32.],
         [13., 23., 33.],
         [14., 24., 34.]]))

### EinSum Notation

In [5]:
A = torch.randn(2,3)
B = torch.randn(2,3)
#C = torch.einsum('ik, kj -> ij', A, B) # Matrix multiplication
D = torch.einsum('ij, ij -> ij', A, B) # Pointwise multiplication (Hadamard product)

In [7]:
D.shape, D

(torch.Size([2, 3]),
 tensor([[-1.4551, -0.9453,  0.1441],
         [-0.0248,  1.0331,  0.1660]]))

In [ ]:
P = torch.randn(2, 3, 4)
Q = torch.randn(2, 4, 5)
torch.einsum("nij, njk -> nik", P, Q) # Multiplication over the last dimension of P and the second-to-last dimension of Q

tensor([[[ 7.4203e-01,  1.9851e+00,  3.8401e-01,  8.5965e-01,  1.7427e+00],
         [-9.7846e-01, -1.3815e-01, -1.1246e+00, -1.3988e+00,  1.8840e+00],
         [ 1.0087e-01, -4.5902e-04,  6.8646e-01, -4.9151e-01, -5.3480e-01]],

        [[-1.6577e+00,  6.1597e-01, -3.2758e+00, -8.7333e-01,  7.9749e-01],
         [-1.5196e-01,  1.6380e-01, -1.1814e+00,  1.1252e+00,  1.0139e+00],
         [-1.1516e+00, -4.8976e-01, -1.2628e+00, -4.7076e-01,  2.1040e-01]]])

## Mean and Standard Deviation

In [12]:
# Create a simple 1D tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
mean = x.mean()
std = x.std()

print("Tensor:", x)
print("Mean:", mean.item())
print("Std:", std.item())

Tensor: tensor([1., 2., 3., 4., 5.])
Mean: 3.0
Std: 1.5811388492584229


In [17]:
# Create a simple 2D tensor (2x3)
x = torch.tensor([
    [1., 2., 3.], 
    [4., 5., 6.]
])

mean_all = x.mean() # equivalent to x.mean(dim=(0,1))
mean_rows = x.mean(dim=1)
mean_cols = x.mean(dim=0)
print("Mean of all elements:", mean_all)
print("Mean per row:", mean_rows)

Mean of all elements: tensor(3.5000)
Mean per row: tensor([2., 5.])


## Batch Normalization

In [ ]:
import torch

B, C, H, W = 8, 3, 64, 64
images = torch.rand(B, C, H, W)
print("Batch shape:", images.shape)

# get images: [B, 3, H, W]
new_mean = torch.mean(images, dim=(0,2,3))
new_std = torch.std(images, dim=(0,2,3))    

print("New mean per channel:", new_mean)
print("New std per channel:", new_std)

# reshape for broadcastinga
new_mean = new_mean.view(1, 3, 1, 1)
new_std = new_std.view(1, 3, 1, 1)

# broadcasting with normalization
images = (images - new_mean) / new_std
print(images)


new_mean = torch.mean(images, dim=(0,2,3))
new_std = torch.std(images, dim=(0,2,3))    
print("Normalized mean per channel:", new_mean)
print("Normalized std per channel:", new_std)

# This is equivalent to using nn.BatchNorm2d(3)(images)

Batch shape: torch.Size([8, 3, 64, 64])
New mean per channel: tensor([0.5003, 0.5003, 0.5009])
New std per channel: tensor([0.2878, 0.2883, 0.2879])
tensor([[[[ 0.8111, -1.2033,  0.6705,  ..., -0.0299,  1.0621, -0.5338],
          [ 0.2736, -0.7234, -0.0206,  ..., -1.0257, -1.3432,  1.3591],
          [ 0.6160, -1.1160, -1.1545,  ...,  0.5482,  1.4651, -0.8601],
          ...,
          [ 1.0516, -1.0016,  0.5921,  ...,  1.1559, -1.5037,  1.3712],
          [ 1.1229,  0.4427,  0.3884,  ...,  1.3442,  0.8616,  1.7144],
          [-0.4826,  1.0073,  0.5562,  ..., -1.4946, -1.5692,  1.2877]],

         [[ 1.5219,  0.6562, -0.7594,  ..., -0.9491,  0.1223, -0.6811],
          [ 0.8699,  1.5331,  0.4966,  ..., -0.7554, -0.5552,  0.4530],
          [ 0.3095, -0.8004, -0.6330,  ...,  1.2054, -0.4074,  0.6588],
          ...,
          [ 1.0892, -1.1951,  1.4752,  ...,  0.8306, -0.1530, -1.7123],
          [ 1.0652, -0.3557, -1.5672,  ...,  0.1661, -1.3406, -1.2413],
          [-1.0202, -1.5046

## Stack vs Cat

In [68]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
# Stack along a new dimension
z = torch.stack((x, y), dim=0)
print(z)
print(z.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [69]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
# Stack along a new dimension
z = torch.cat((x, y), dim=0)
print(z)
print(z.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


---
# Exercise: Multi-Head Self Attention
---

Implement a **mini multi-head attention block** *from scratch*, using only:
- tensor reshaping (`view`, `reshape`, `transpose`, `permute`)
- batched matrix multiplication (`matmul`)
- broadcasting

#### Setup

- batch size $B = 4$
- sequence length $T = 16$
- embedding dimension $D = 64$
- number of heads $H = 8$ (so head dimension $d = D/H$)
- create:
    - input tensor $x$ with shape $(B, T, D)$
    - learnable projection matrices $Wq, Wk, Wv, Wo$, with shapes $(D, D)$

#### Tasks

1) **Create the input**
2) **Compute Q, K, V**
3) **Split into heads**
4) **Compute attention scores**
5) **Softmax + weighted sum**
6) **Merge heads**
7) **Output projection**


In [98]:
# 0. Setup
B = 4
T = 16
D = 64
H = 8
d = D // H

# 1. Create the input
x = torch.randn((B, T, D))
Wq = torch.randn((D, D))
Wk = torch.randn((D, D))
Wv = torch.randn((D, D))
Wo = torch.randn((D, D))

# 2. Compiute Q, K, V
Q = x @ Wq # Shapes: (B, T, D) @ (D, D) -> (B, T, D)
K = x @ Wk # ...
V = x @ Wv # ...

# 3. Split into heads
Qh = Q.view(B, T, H, d) # Shapes: (B, T, D) -> (B, T, H, d) basically we are splitting the last dim (D) into two
Qh = Qh.transpose(1, 2) # Shapes: (B, T, H, d) -> (B, H, T, d) we want heads to be the second dimension
# This way, we can imagine having Txd matrices for each head (for each batch item)
Kh = K.view(B, T, H, d).transpose(1, 2)
Vh = V.view(B, T, H, d).transpose(1, 2)

# 4. Compute Attention Scores
Kh_t = Kh.transpose(-2, -1) # Inverts the last and second to last dimensions
S = (Qh @ Kh_t) / (d ** 0.5) # Shapes: (B, H, T, d) @ (B, H, d, T) -> (B, H, T, T) these are attention scores! token vs token

# 5. Softmax + weighted sum
A = torch.softmax(S, dim=-1) # Softmax on the weights, does not affect shape.
Oh = A @ Vh # Shapes: (B, H, T, T) @ (B, H, T, d) -> (B, H, T, d) back to original shape!

# 6. Merge heads
out = Oh.transpose(1, 2).reshape(B, T, D) # Shapes: (B, H, T, d) -> (B, T, H, d) -> (B, T, D)
# Basically I first put H and d back together as dimensions, then I collapse them into D. 

# 7. Output projection
y = out @ Wo # Shapes (B, T, D) @ (D, D) -> (B, T, D) no effect on the shape

print(f"x shape: {x.shape}")
print(f"Qh shape: {Qh.shape}")
print(f"S shape: {S.shape}")
print(f"A shape: {A.shape}")
print(f"Oh shape: {Oh.shape}")
print(f"y shape: {y.shape}")

x shape: torch.Size([4, 16, 64])
Qh shape: torch.Size([4, 8, 16, 8])
S shape: torch.Size([4, 8, 16, 16])
A shape: torch.Size([4, 8, 16, 16])
Oh shape: torch.Size([4, 8, 16, 8])
y shape: torch.Size([4, 16, 64])


In [93]:
A = torch.randn(4, 2, 3)

print(A)
B = A.reshape(4, 6)
print(B)

tensor([[[-0.3755,  1.5494, -0.0113],
         [-0.0815, -2.1059, -0.2385]],

        [[-0.1380, -0.7703,  1.3177],
         [-1.7765,  0.6916,  1.1527]],

        [[-0.9834, -1.1458,  1.3966],
         [-0.8209, -1.1417,  0.0119]],

        [[-0.3481, -0.5715,  0.4604],
         [ 0.0088, -0.7844, -0.2978]]])
tensor([[-0.3755,  1.5494, -0.0113, -0.0815, -2.1059, -0.2385],
        [-0.1380, -0.7703,  1.3177, -1.7765,  0.6916,  1.1527],
        [-0.9834, -1.1458,  1.3966, -0.8209, -1.1417,  0.0119],
        [-0.3481, -0.5715,  0.4604,  0.0088, -0.7844, -0.2978]])
